In [3]:
import torch

# input tensor
x = torch.ones(5)

# output tensor
y = torch.zeros(3)

# requires_grad = True -> backpropagation
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b

# compare with prediction model and calculate the loss
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

print(loss)

tensor(1.1924, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [4]:
# calculate the gradient

loss.backward()

print(w.grad)
print(b.grad)

tensor([[0.2351, 0.2996, 0.0213],
        [0.2351, 0.2996, 0.0213],
        [0.2351, 0.2996, 0.0213],
        [0.2351, 0.2996, 0.0213],
        [0.2351, 0.2996, 0.0213]])
tensor([0.2351, 0.2996, 0.0213])


In [7]:
# stop requires_grad

# 1
z = torch.matmul(x, w) + b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w) + b

print(z.requires_grad)

# 2

z = torch.matmul(x, w) + b
print(z.requires_grad)

z = torch.matmul(x, w) + b
z_det = z.detach()

print(z_det.requires_grad)

True
False
True
False


In [11]:
# Jacobian matrix

inp = torch.eye(4, 5, requires_grad=True)
out = (inp + 1).pow(2).t()

out.backward(torch.ones_like(out), retain_graph=True)

print(f'First: \n {inp.grad}')

out.backward(torch.ones_like(out), retain_graph=True)

print(f'Second: \n {inp.grad}')

inp.grad.zero_()

out.backward(torch.ones_like(out), retain_graph=True)

print(f'Call after zeroing gradients: \n {inp.grad}')


First: 
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
Second: 
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])
Call after zeroing gradients: 
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
