In [2]:
# import

import torch
import numpy as np


In [4]:
# initialize 

data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)

print(x_data)


tensor([[1, 2],
        [3, 4]])


In [9]:
# create from numpy array

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [12]:
# Ones Tensor and Random Tensor
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0246, 0.4005],
        [0.5761, 0.3865]]) 



Difference between rand() and rand_like()

The parameter of rand() is size.
The parameter of rand_like() is tensor.

Both of them create a new tensor with same size with their parameter.

In [18]:
# dimention(tuple)
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor} \n')

Random Tensor: 
 tensor([[0.3938, 0.7430, 0.0057],
        [0.1476, 0.4206, 0.1881]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [21]:
tensor = torch.rand(3, 4)

print(f'Shape of tensor: {tensor.shape}')
print(f'Datatype of tensor: {tensor.dtype}')
print(f'Device tensor is stored on: {tensor.device}')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [26]:
tensor = torch.ones(4, 4)

print(f'First row: {tensor[0]}')
print(f'First col: {tensor[:,0]}')
print(f'Last col: {tensor[...,-1]}')
tensor[:,1] = 0

print(tensor)


First row: tensor([1., 1., 1., 1.])
First col: tensor([1., 1., 1., 1.])
Last col: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [32]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
t2 = torch.cat([tensor, tensor, tensor], dim = 0)

print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [45]:
# mul of matrix @ or matmul()

data = [[1.,2.], [3.,4.]]
tensor = torch.tensor(data)

# tensor = torch.rand(3,3)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out = y3) 

print(y1)
print(y2)
print(y3, end='\n ---------------- \n')


# element wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[ 5., 11.],
        [11., 25.]])
tensor([[ 5., 11.],
        [11., 25.]])
tensor([[ 5., 11.],
        [11., 25.]])
 ---------------- 
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [47]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

10.0 <class 'float'>


In [49]:
# in-place

print(f'{tensor} \n')

tensor.add_(5)
print(tensor)

tensor.copy_(z3)
print(tensor)

tensor([[6., 7.],
        [8., 9.]]) 

tensor([[11., 12.],
        [13., 14.]])
tensor([[ 1.,  4.],
        [ 9., 16.]])


In [51]:
# Bridge tensor to numpy

t = torch.ones(5)
print(f't: {t}')

n = t.numpy()
print(f'n: {n}')


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [52]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [53]:
print(f'n: {n}')

n: [2. 2. 2. 2. 2.]


In [55]:
# Bridge numpy to tensor

n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out = n)

print(f't: {t}')

print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
